// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsConcentratorSystem.Models;

namespace NewsConcentratorSystem.Migrations
{
    [DbContext(typeof(NewsConcentratorDbContext))]
    [Migration("20210420105445_PublishedNewsesEntityAdded")]
    partial class PublishedNewsesEntityAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("NewsConcentratorSystem.Models.MessageCutAfter", b =>
                {
                    b.Property<int>("MCAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CutAfterWord")
                        .HasColumnType("TEXT");

                    b.HasKey("MCAId");

                    b.ToTable("MessageCutAfters");
                });

            modelBuilder.Entity("NewsConcentratorSystem.Models.MessageMustContain", b =>
                {
                    b.Property<int>("MMCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MustContainWord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TelegramChannelChannelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MMCId");

                    b.HasIndex("TelegramChannelChannelId");

                    b.ToTable("MessageMustContains");
                });

            modelBuilder.Entity("NewsConcentratorSystem.Models.MessageMustnotContainFilter", b =>
                {
                    b.Property<int>("MMCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MustnotContainWord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TelegramChannelChannelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MMCId");

                    b.HasIndex("TelegramChannelChannelId");

                    b.ToTable("MessageMustnotContain");
                });

            modelBuilder.Entity("NewsConcentratorSystem.Models.MessageReplaceWord", b =>
                {
                    b.Property<int>("MRWId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplaceTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TelegramChannelChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MRWId");

                    b.HasIndex("TelegramChannelChannelId");

                    b.ToTable("MessageReplaceWords");
                });

            modelBuilder.Entity("NewsConcentratorSystem.Models.PublishedNewses", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mediahash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextMessage")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("PublishedNewseses");
                });

            modelBuilder.Entity("NewsConcentratorSystem.Models.Settings", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("NewsConcentratorSystem.Models.TelegramChannel", b =>
                {
                    b.Property<int>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelChatID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("NewsConcentratorSystem.Models.MessageMustContain", b =>
                {
                    b.HasOne("NewsConcentratorSystem.Models.TelegramChannel", null)
                        .WithMany("MustContainWords")
                        .HasForeignKey("TelegramChannelChannelId");
                });

            modelBuilder.Entity("NewsConcentratorSystem.Models.MessageMustnotContainFilter", b =>
                {
                    b.HasOne("NewsConcentratorSystem.Models.TelegramChannel", null)
                        .WithMany("MustnotContainFilters")
                        .HasForeignKey("TelegramChannelChannelId");
                });

            modelBuilder.Entity("NewsConcentratorSystem.Models.MessageReplaceWord", b =>
                {
                    b.HasOne("NewsConcentratorSystem.Models.TelegramChannel", null)
                        .WithMany("ReplaceWords")
                        .HasForeignKey("TelegramChannelChannelId");
                });

            modelBuilder.Entity("NewsConcentratorSystem.Models.TelegramChannel", b =>
                {
                    b.Navigation("MustContainWords");

                    b.Navigation("MustnotContainFilters");

                    b.Navigation("ReplaceWords");
                });
#pragma warning restore 612, 618
        }
    }
}
